VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here.

  # !!!
  # CHOOSE BASEBOX
  # !!!

  config.vm.box = "jansauer/fedora22-core"
  #config.vm.box = "jansauer/centos7-core"

end
